### ISSUE TITLE
Changing a nested Hash with Rails 4.2 leads to invalid conversion

### ISSUE THREAD

**Issue by dspaeth-faber** [tombenner/nested-hstore#14]
Hi,

with Rails 4.2 the following does not work anymore

```ruby
post = Post.new
post.attributes = { nested_hash: {"a"=>[{"b"=>"c"}]}}
post.save!

loaded_post = Post.find post.id

loaded_post .nested_hash['a'][0]['new_key'] = 12345
loaded_post .save!

loaded_post = Post.find post.id

loaded_post .nested_hash # value is now a string and not an Array =>  'a' => "['b' => 'c', 'new_key' => 12345]" 


```

regards 
dieter

**Comment by tombenner** [comment]
Hm, I haven't been able to reproduce this, either in a Rails 4.2 app or in the test suite with a Rails 4.2 appraisal. Are you sure that you've included the following line in your Post model?

```ruby
serialize :nested_hash, ActiveRecord::Coders::NestedHstore
```

If that looks good, could you either add a failing test to the test suite (you can add a new appraisal that includes Rails 4 in the [Appraisals file](https://github.com/tombenner/nested-hstore/blob/master/Appraisals)) or publish a simple demo app of it failing?

**Comment by dspaeth-faber** [comment]
It's a realy ugly thing. Within the specs of nested-hostre I can't reproduce it either. But within my project I get every time the same result. So I think it has some thing to do with the other gems I use. When I have any further informations, I will report back.

**Comment by dspaeth-faber** [comment]
What is realy strange, after the save in my case the hstore value does in the database not look like json, instead it looks like a Hash with rockets. Also after the load `deserialize` is not called.

**Comment by tombenner** [comment]
It sounds like `ActiveRecord::Coders::NestedHstore` probably isn't being used as the coder. Let me know what you find. One simple approach might be to remove any other gems (especially ActiveRecord-related ones) and see if that resolves it.

**Comment by dspaeth-faber** [comment]
Now I got it! You can see it in my [fork](https://github.com/dspaeth-faber/nested-hstore/tree/deserialize_error). The issue arises as soon as you add

```ruby
      t.timestamps
      t.integer :lock_version, default: 0, null: false
```

to your db-table.

**Comment by dspaeth-faber** [comment]
I did file a Rails issue rails/rails#18506.

**Comment by tombenner** [comment]
Closing, as this is a Rails issue. Thanks for looking into it!
